# Generated by Django 3.1.7 on 2021-04-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0004_auto_20210430_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
