# Generated by Django 3.1.7 on 2021-05-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0006_remove_item_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Image',
        ),
    ]
